// Phase 2: Feature usage tracking & PMF instrumentation
// Lightweight client-side analytics that logs to Supabase feature_events table

import { supabase } from './supabase';

let sessionId: string | null = null;

function getSessionId(): string {
  if (!sessionId) {
      sessionId = `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
        }
          return sessionId;
          }

          interface TrackEventOptions {
            category?: string;
              data?: Record<string, unknown>;
              }

              // Fire-and-forget event tracking - never blocks UI
              export function trackEvent(eventName: string, options: TrackEventOptions = {}) {
                const { category = 'feature', data = {} } = options;

                  // Non-blocking async call
                    (async () => {
                        try {
                              const { data: { session } } = await supabase.auth.getSession();
                                    if (!session) return;

                                          await supabase.from('feature_events').insert({
                                                  user_id: session.user.id,
                                                          event_name: eventName,
                                                                  event_category: category,
                                                                          event_data: data,
                                                                                  session_id: getSessionId(),
                                                                                        });
                                                                                            } catch {
                                                                                                  // Silently fail - analytics should never break the app
                                                                                                      }
                                                                                                        })();
                                                                                                        }

                                                                                                        // Track page/tab views
                                                                                                        export function trackPageView(tabName: string) {
                                                                                                          trackEvent('page_view', { category: 'navigation', data: { tab: tabName } });
                                                                                                          }

                                                                                                          // Track feature engagement
                                                                                                          export function trackFeatureUse(feature: string, action: string = 'open') {
                                                                                                            trackEvent(`feature_${action}`, { category: 'feature', data: { feature } });
                                                                                                            }

                                                                                                            // Track search queries
                                                                                                            export function trackSearch(query: string, resultCount: number) {
                                                                                                              trackEvent('search', { category: 'engagement', data: { query_length: query.length, result_count: resultCount } });
                                                                                                              }

                                                                                                              // Track WhatsApp connection events
                                                                                                              export function trackBridgeEvent(status: string) {
                                                                                                                trackEvent('bridge_status', { category: 'connection', data: { status } });
                                                                                                                }

                                                                                                                // Track AI assistant interactions
                                                                                                                export function trackAssistantQuery(queryLength: number, responseTime: number) {
                                                                                                                  trackEvent('assistant_query', { category: 'ai', data: { query_length: queryLength, response_time_ms: responseTime } });
                                                                                                                  }

                                                                                                                  // Track activation milestones
                                                                                                                  export function trackActivation(milestone: string) {
                                                                                                                    trackEvent('activation_milestone', { category: 'activation', data: { milestone } });
                                                                                                                    }

                                                                                                                    // Update user streak (calls API)
                                                                                                                    export async function updateStreak() {
                                                                                                                      try {
                                                                                                                          const { data: { session } } = await supabase.auth.getSession();
                                                                                                                              if (!session) return;

                                                                                                                                  const today = new Date().toISOString().split('T')[0];

                                                                                                                                      const { data: existing } = await supabase
                                                                                                                                            .from('engagement_streaks')
                                                                                                                                                  .select('*')
                                                                                                                                                        .eq('user_id', session.user.id)
                                                                                                                                                              .eq('streak_type', 'daily_login')
                                                                                                                                                                    .single();

                                                                                                                                                                        if (!existing) {
                                                                                                                                                                              await supabase.from('engagement_streaks').insert({
                                                                                                                                                                                      user_id: session.user.id,
                                                                                                                                                                                              streak_type: 'daily_login',
                                                                                                                                                                                                      current_streak: 1,
                                                                                                                                                                                                              longest_streak: 1,
                                                                                                                                                                                                                      last_activity_date: today,
                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                          const lastDate = existing.last_activity_date;
                                                                                                                                                                                                                                              if (lastDate === today) return; // Already tracked today

                                                                                                                                                                                                                                                  const yesterday = new Date();
                                                                                                                                                                                                                                                      yesterday.setDate(yesterday.getDate() - 1);
                                                                                                                                                                                                                                                          const yesterdayStr = yesterday.toISOString().split('T')[0];

                                                                                                                                                                                                                                                              const newStreak = lastDate === yesterdayStr ? existing.current_streak + 1 : 1;
                                                                                                                                                                                                                                                                  const longestStreak = Math.max(newStreak, existing.longest_streak);

                                                                                                                                                                                                                                                                      await supabase
                                                                                                                                                                                                                                                                            .from('engagement_streaks')
                                                                                                                                                                                                                                                                                  .update({
                                                                                                                                                                                                                                                                                          current_streak: newStreak,
                                                                                                                                                                                                                                                                                                  longest_streak: longestStreak,
                                                                                                                                                                                                                                                                                                          last_activity_date: today,
                                                                                                                                                                                                                                                                                                                  updated_at: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                              .eq('id', existing.id);

                                                                                                                                                                                                                                                                                                                                  // Track streak milestone events
                                                                                                                                                                                                                                                                                                                                      if (newStreak === 3) trackActivation('streak_3_days');
                                                                                                                                                                                                                                                                                                                                          if (newStreak === 7) trackActivation('streak_7_days');
                                                                                                                                                                                                                                                                                                                                              if (newStreak === 30) trackActivation('streak_30_days');
                                                                                                                                                                                                                                                                                                                                                } catch {
                                                                                                                                                                                                                                                                                                                                                    // Silent fail
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                      // Update last_active_at on users table
                                                                                                                                                                                                                                                                                                                                                      export async function updateLastActive() {
                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                            const { data: { session } } = await supabase.auth.getSession();
                                                                                                                                                                                                                                                                                                                                                                if (!session) return;

                                                                                                                                                                                                                                                                                                                                                                    await supabase
                                                                                                                                                                                                                                                                                                                                                                          .from('users')
                                                                                                                                                                                                                                                                                                                                                                                .update({ last_active_at: new Date().toISOString() })
                                                                                                                                                                                                                                                                                                                                                                                      .eq('id', session.user.id);
                                                                                                                                                                                                                                                                                                                                                                                        } catch {
                                                                                                                                                                                                                                                                                                                                                                                            // Silent fail
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                              }import { supabaseAdmin } from '@/lib/supabase';import { withAuth, apiSuccess, apiError } from '@/lib/api-utils';// Phase 3: Relationship Intelligence Graph// GET /api/relationship-scores - Get relationship scores for userexport const GET = withAuth(async (req: NextRequest, { user }) => {  try {    const url = new URL(req.url);    const limit = parseInt(url.searchParams.get('limit') || '20');    const sortBy = url.searchParams.get('sort') || 'score';    const { data, error } = await supabaseAdmin      .from('relationship_scores')      .select('*')      .eq('user_id', user.id)      .order(sortBy === 'recent' ? 'last_interaction_at' : 'score', { ascending: false })      .limit(limit);
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                  if (error) throw error;
                                                                                                                                                                                                                                                                                                                                                                                                      return apiSuccess(data || []);
                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                            console.error('[RelationshipScores] GET error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                return apiError('Failed to fetch relationship scores', 500);
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                  // POST /api/relationship-scores - Recalculate relationship scores
                                                                                                                                                                                                                                                                                                                                                                                                                  export const POST = withAuth(async (req: NextRequest, { user }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                        // Get all contacts with message counts
                                                                                                                                                                                                                                                                                                                                                                                                                            const { data: contacts } = await supabaseAdmin
                                                                                                                                                                                                                                                                                                                                                                                                                                  .from('contacts')
                                                                                                                                                                                                                                                                                                                                                                                                                                        .select('id, name, display_name')
                                                                                                                                                                                                                                                                                                                                                                                                                                              .eq('user_id', user.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!contacts || contacts.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        return apiSuccess({ updated: 0 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const thirtyDaysAgo = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let updated = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (const contact of contacts) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Get message stats for this contact
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const { data: messages } = await supabaseAdmin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .from('messages')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .select('id, created_at, is_from_me')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .eq('user_id', user.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .eq('contact_id', contact.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .gte('created_at', thirtyDaysAgo.toISOString())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .order('created_at', { ascending: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!messages || messages.length === 0) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const interactionCount = messages.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const lastMessage = messages[messages.length - 1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Calculate response time
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      let totalResponseTime = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let responseCount = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for (let i = 0; i < messages.length - 1; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!messages[i].is_from_me && messages[i + 1].is_from_me) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const diff = (new Date(messages[i + 1].created_at).getTime() - new Date(messages[i].created_at).getTime()) / 60000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (diff > 0 && diff < 1440) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          totalResponseTime += diff;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      responseCount++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const avgResponseTime = responseCount > 0 ? totalResponseTime / responseCount : null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Calculate score (0-100): weighted combination
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const recencyScore = Math.max(0, 30 - ((Date.now() - new Date(lastMessage.created_at).getTime()) / (1000 * 60 * 60 * 24)));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const volumeScore = Math.min(40, interactionCount * 2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const responseScore = avgResponseTime ? Math.max(0, 30 - (avgResponseTime / 60)) : 15;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const score = Math.min(100, Math.round(recencyScore + volumeScore + responseScore));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Upsert relationship score
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await supabaseAdmin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .from('relationship_scores')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .upsert({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        user_id: user.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  contact_id: contact.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            contact_name: contact.display_name || contact.name || 'Unknown',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      score,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                interaction_count: interactionCount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          last_interaction_at: lastMessage.created_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    avg_response_time_min: avgResponseTime ? Math.round(avgResponseTime * 100) / 100 : null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              updated_at: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, { onConflict: 'user_id,contact_id' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updated++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return apiSuccess({ updated, total_contacts: contacts.length });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.error('[RelationshipScores] POST error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return apiError('Failed to calculate scores', 500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });import { useState, useEffect } from }})