'use client';

import React from 'react';
import {
  Home,
    MessageCircle,
      ListChecks,
        Users,
          Sparkles,
            Settings,
              ChevronLeft,
                ChevronRight,
                  Command,
                  } from 'lucide-react';
                  import { TabType } from '@/types/dashboard';
                  
                  interface DashboardSidebarProps {
                    activeTab: TabType;
                      onTabChange: (tab: TabType) => void;
                        collapsed: boolean;
                          onToggleCollapse: () => void;
                          }
                          
                          interface NavItem {
                            icon: React.ElementType;
                              label: string;
                                tab: TabType;
                                  description?: string;
                                    badge?: number;
                                    }
                                    
                                    const navItems: NavItem[] = [
                                      { icon: Home, label: 'Home', tab: 'home', description: 'Your daily brief' },
                                        { icon: MessageCircle, label: 'Messages', tab: 'messages', description: 'Chats, files & search' },
                                          { icon: ListChecks, label: 'Actions', tab: 'actions', description: 'Reminders & tasks' },
                                            { icon: Users, label: 'People', tab: 'people', description: 'Contact intelligence' },
                                              { icon: Sparkles, label: 'Assistant', tab: 'assistant', description: 'AI-powered search' },
                                              ];
                                              
                                              const DashboardSidebar: React.FC<DashboardSidebarProps> = ({
                                                activeTab,
                                                  onTabChange,
                                                    collapsed,
                                                      onToggleCollapse,
                                                      }) => {
                                                        return (
                                                            <aside
                                                                  className={`hidden md:flex flex-col flex-shrink-0 bg-slate-950 border-r border-slate-800/50 transition-all duration-300 ease-in-out relative ${
                                                                          collapsed ? 'w-[72px]' : 'w-[240px]'
                                                                                }`}
                                                                                    >
                                                                                          {/* Collapse toggle */}
                                                                                                <button
                                                                                                        onClick={onToggleCollapse}
                                                                                                                className="absolute -right-3 top-7 z-10 w-6 h-6 bg-slate-800 border border-slate-700 rounded-full flex items-center justify-center text-slate-400 hover:bg-slate-700 hover:text-white transition-colors shadow-lg"
                                                                                                                        aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}
                                                                                                                              >
                                                                                                                                      {collapsed ? <ChevronRight size={12} /> : <ChevronLeft size={12} />}
                                                                                                                                            </button>
                                                                                                                                            
                                                                                                                                                  {/* Keyboard shortcut hint */}
                                                                                                                                                        {!collapsed && (
                                                                                                                                                                <div className="mx-3 mt-5 mb-2">
                                                                                                                                                                          <button
                                                                                                                                                                                      onClick={() => onTabChange('assistant')}
                                                                                                                                                                                                  className="w-full flex items-center gap-2 px-3 py-2 rounded-lg bg-slate-900 border border-slate-800 text-slate-500 hover:text-slate-300 hover:border-slate-700 transition-all text-xs"
                                                                                                                                                                                                            >
                                                                                                                                                                                                                        <Command size={13} />
                                                                                                                                                                                                                                    <span>Search anything...</span>
                                                                                                                                                                                                                                                <kbd className="ml-auto text-[10px] bg-slate-800 text-slate-500 px-1.5 py-0.5 rounded font-mono">⌘K</kbd>
                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                              {/* Main Navigation */}
                                                                                                                                                                                                                                                                                    <nav className="flex-1 px-3 py-2 space-y-1">
                                                                                                                                                                                                                                                                                            {navItems.map((item) => {
                                                                                                                                                                                                                                                                                                      const isActive = activeTab === item.tab;
                                                                                                                                                                                                                                                                                                                const Icon = item.icon;
                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                    key={item.tab}
                                                                                                                                                                                                                                                                                                                                                                  onClick={() => onTabChange(item.tab)}
                                                                                                                                                                                                                                                                                                                                                                                title={collapsed ? item.label : undefined}
                                                                                                                                                                                                                                                                                                                                                                                              className={`w-full flex items-center gap-3 rounded-xl transition-all duration-150 group relative ${
                                                                                                                                                                                                                                                                                                                                                                                                              collapsed ? 'justify-center px-2 py-3' : 'px-3 py-2.5'
                                                                                                                                                                                                                                                                                                                                                                                                                            } ${
                                                                                                                                                                                                                                                                                                                                                                                                                                            isActive
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? 'bg-white/[0.08] text-white'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : 'text-slate-400 hover:bg-white/[0.04] hover:text-slate-200'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {isActive && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="absolute left-0 top-1/2 -translate-y-1/2 w-[3px] h-5 bg-emerald-400 rounded-r-full" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={`flex-shrink-0 ${isActive ? 'text-emerald-400' : 'text-slate-500 group-hover:text-slate-300'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Icon size={20} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {!collapsed && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex flex-col items-start min-w-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className={`text-[13px] font-semibold leading-tight ${isActive ? 'text-white' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-[11px] text-slate-600 leading-tight truncate">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {item.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Settings — pinned bottom */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="border-t border-slate-800/60 p-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => onTabChange('settings')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title={collapsed ? 'Settings' : undefined}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`w-full flex items-center gap-3 rounded-xl transition-all duration-150 group ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                collapsed ? 'justify-center px-2 py-2.5' : 'px-3 py-2.5'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      activeTab === 'settings'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? 'bg-white/[0.08] text-white'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : 'text-slate-400 hover:bg-white/[0.04] hover:text-slate-200'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Settings
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          size={20}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    activeTab === 'settings'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? 'text-emerald-400'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : 'text-slate-500 group-hover:text-slate-300'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {!collapsed && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className={`text-[13px] font-semibold ${activeTab === 'settings' ? 'text-white' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Settings
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </aside>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default DashboardSidebar;