'use client';

import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/lib/supabase';
import { MessageSquare, LogOut } from 'lucide-react';
import { TabType } from '@/types/dashboard';

import DashboardSidebar from '@/components/DashboardSidebar';
import MobileTabBar from '@/components/MobileTabBar';

import HomeSection from '@/components/dashboard/HomeSection';
import MessagesSection from '@/components/dashboard/MessagesSection';
import ActionsSection from '@/components/dashboard/ActionsSection';
import PeopleSection from '@/components/dashboard/PeopleSection';
import AssistantSection from '@/components/dashboard/AssistantSection';
import SettingsSection from '@/components/dashboard/SettingsSection';

interface BridgeStatus {
  connected: boolean;
    phone?: string;
      name?: string;
      }
      
      const BRIDGE_URL = process.env.NEXT_PUBLIC_BRIDGE_URL || 'https://chatvault-ai-production.up.railway.app';
      
      // Map legacy tab names to new ones
      function resolveTab(hash: string): TabType {
        const legacyMap: Record<string, TabType> = {
            search: 'messages',
                chats: 'messages',
                    attachments: 'messages',
                        summaries: 'messages',
                            contacts: 'people',
                                sentiment: 'people',
                                    labels: 'messages',
                                        reminders: 'actions',
                                            commitments: 'actions',
                                                templates: 'messages',
                                                    analytics: 'home',
                                                        reports: 'home',
                                                          };
                                                            if (legacyMap[hash]) return legacyMap[hash];
                                                              const validTabs: TabType[] = ['home', 'messages', 'actions', 'people', 'assistant', 'settings'];
                                                                return validTabs.includes(hash as TabType) ? (hash as TabType) : 'home';
                                                                }
                                                                
                                                                function getTabFromHash(): TabType {
                                                                  if (typeof window === 'undefined') return 'home';
                                                                    const hash = window.location.hash.replace('#', '');
                                                                      return resolveTab(hash);
                                                                      }
                                                                      
                                                                      export default function DashboardPage() {
                                                                        const [activeTab, setActiveTab] = useState<TabType>('home');
                                                                          const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
                                                                            const [user, setUser] = useState<any>(null);
                                                                              const [userName, setUserName] = useState<string>('');
                                                                                const [bridgeStatus, setBridgeStatus] = useState<BridgeStatus>({ connected: false });
                                                                                
                                                                                  useEffect(() => {
                                                                                      setActiveTab(getTabFromHash());
                                                                                          const handleHashChange = () => setActiveTab(getTabFromHash());
                                                                                              window.addEventListener('hashchange', handleHashChange);
                                                                                                  return () => window.removeEventListener('hashchange', handleHashChange);
                                                                                                    }, []);
                                                                                                    
                                                                                                      const handleTabChange = useCallback((tab: TabType) => {
                                                                                                          const resolved = resolveTab(tab);
                                                                                                              setActiveTab(resolved);
                                                                                                                  window.location.hash = resolved;
                                                                                                                    }, []);
                                                                                                                    
                                                                                                                      // Cmd+K shortcut to open assistant
                                                                                                                        useEffect(() => {
                                                                                                                            const handleKeyDown = (e: KeyboardEvent) => {
                                                                                                                                  if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
                                                                                                                                          e.preventDefault();
                                                                                                                                                  handleTabChange('assistant');
                                                                                                                                                        }
                                                                                                                                                            };
                                                                                                                                                                window.addEventListener('keydown', handleKeyDown);
                                                                                                                                                                    return () => window.removeEventListener('keydown', handleKeyDown);
                                                                                                                                                                      }, [handleTabChange]);
                                                                                                                                                                      
                                                                                                                                                                        useEffect(() => {
                                                                                                                                                                            const checkBridge = async () => {
                                                                                                                                                                                  try {
                                                                                                                                                                                          const res = await fetch(BRIDGE_URL + '/status');
                                                                                                                                                                                                  const data = await res.json();
                                                                                                                                                                                                          setBridgeStatus(prev => {
                                                                                                                                                                                                                    if (prev.connected !== data.connected || prev.phone !== data.phone || prev.name !== data.name) {
                                                                                                                                                                                                                                return { connected: data.connected, phone: data.phone, name: data.name };
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                    return prev;
                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                  } catch {
                                                                                                                                                                                                                                                                          setBridgeStatus(prev => prev.connected ? { connected: false } : prev);
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                        checkBridge();
                                                                                                                                                                                                                                                                                            const interval = setInterval(checkBridge, 30000);
                                                                                                                                                                                                                                                                                                return () => clearInterval(interval);
                                                                                                                                                                                                                                                                                                  }, []);
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                    useEffect(() => { checkAuth(); }, []);
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                      async function checkAuth() {
                                                                                                                                                                                                                                                                                                          const { data: { user: authUser } } = await supabase.auth.getUser();
                                                                                                                                                                                                                                                                                                              if (!authUser) { window.location.href = '/login'; return; }
                                                                                                                                                                                                                                                                                                                  setUser(authUser);
                                                                                                                                                                                                                                                                                                                      const { data: profile } = await supabase
                                                                                                                                                                                                                                                                                                                            .from('users')
                                                                                                                                                                                                                                                                                                                                  .select('display_name')
                                                                                                                                                                                                                                                                                                                                        .eq('auth_id', authUser.id)
                                                                                                                                                                                                                                                                                                                                              .single();
                                                                                                                                                                                                                                                                                                                                                  if (profile?.display_name && profile.display_name !== 'WhatsApp User') {
                                                                                                                                                                                                                                                                                                                                                        setUserName(profile.display_name.split(' ')[0]);
                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                  const metaName = authUser.user_metadata?.full_name || authUser.user_metadata?.name;
                                                                                                                                                                                                                                                                                                                                                                        setUserName(metaName ? metaName.split(' ')[0] : (authUser.email?.split('@')[0] || ''));
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                async function handleSignOut() {
                                                                                                                                                                                                                                                                                                                                                                                    await supabase.auth.signOut();
                                                                                                                                                                                                                                                                                                                                                                                        window.location.href = '/login';
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                            const renderSection = () => {
                                                                                                                                                                                                                                                                                                                                                                                                switch (activeTab) {
                                                                                                                                                                                                                                                                                                                                                                                                      case 'home': return <HomeSection onNavigate={handleTabChange} />;
                                                                                                                                                                                                                                                                                                                                                                                                            case 'messages': return <MessagesSection />;
                                                                                                                                                                                                                                                                                                                                                                                                                  case 'actions': return <ActionsSection />;
                                                                                                                                                                                                                                                                                                                                                                                                                        case 'people': return <PeopleSection />;
                                                                                                                                                                                                                                                                                                                                                                                                                              case 'assistant':
                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                <AssistantSection
                                                                                                                                                                                                                                                                                                                                                                                                                                                            bridgeStatus={bridgeStatus.connected ? 'connected' : 'disconnected'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        userEmail={user?.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    userName={userName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case 'settings': return <SettingsSection />;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  default: return <HomeSection onNavigate={handleTabChange} />;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="h-screen flex flex-col bg-slate-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Header */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <header className="bg-white border-b border-slate-200/80 px-4 md:px-6 flex-shrink-0 z-20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center justify-between h-14">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-2.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="w-8 h-8 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-lg flex items-center justify-center shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <MessageSquare className="w-4 h-4 text-white" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h1 className="text-lg font-bold text-slate-900 tracking-tight">Rememora</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {bridgeStatus.connected ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-2 bg-emerald-50 border border-emerald-200 rounded-full px-3 py-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-xs text-emerald-700 font-medium hidden sm:inline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {bridgeStatus.name || bridgeStatus.phone || 'Connected'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href="/dashboard/connect"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="flex items-center gap-2 bg-amber-50 border border-amber-200 rounded-full px-3 py-1 hover:bg-amber-100 transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="w-2 h-2 bg-amber-400 rounded-full" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-xs text-amber-700 font-medium hidden sm:inline">Connect WhatsApp</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-xs text-slate-400 hidden md:inline">{user?.email}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={handleSignOut}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="text-slate-400 hover:text-slate-600 transition-colors p-1.5 hover:bg-slate-100 rounded-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title="Sign out"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <LogOut className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex flex-1 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <DashboardSidebar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      activeTab={activeTab}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onTabChange={handleTabChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          collapsed={sidebarCollapsed}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onToggleCollapse={() => setSidebarCollapsed(!sidebarCollapsed)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <main className="flex-1 overflow-y-auto pb-20 md:pb-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="max-w-6xl mx-auto px-4 md:px-8 py-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {renderSection()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <MobileTabBar activeTab={activeTab} onTabChange={handleTabChange} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }